import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import HelloPage from '../features/counter/pages/HelloPage'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark:bg-slate-800">
        <div className="flex justify-center flex-col items-center gap-4 my">
          <HelloPage />
        </div>
      </main>
    </>
  )
}
